packages:
  - apps/*
  - packages/*

allowedDeprecatedVersions:
  glob: 7.2.3
  inflight: 1.0.6
  lodash.get: 4.4.2
  rimraf: 3.0.2

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - simple-git-hooks
  - vue-demi

patchedDependencies:
  plop@4.0.2: patches/plop@4.0.2.patch

shamefullyHoist: true
