name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # To use Turborepo Remote Caching, uncomment the next lines and follow the steps below.
      # See https://turbo.build/docs/guides/ci-vendors/github-actions#remote-caching
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: pnpm test

      - name: Run build
        run: pnpm build
