name: Publish GitHub Container Registry

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  REPOSITORY: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      # To use Turborepo Remote Caching, uncomment the next lines and follow the steps below.
      # See https://turbo.build/docs/guides/ci-vendors/github-actions#remote-caching
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get tag and set to env
        id: tag
        run: |
          RAW_TAG=${{ github.ref_name }}
          CLEAN_TAG=${RAW_TAG#v}
          echo "TAG=$CLEAN_TAG" >> $GITHUB_ENV
          echo "Using tag: $CLEAN_TAG"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: |
          echo "Building..."

          echo "————————————————————————————————————————————————————————————"
          echo "  Repo name: $REPO_NAME"
          echo " Repository: $REPOSITORY"
          echo "        Tag: $TAG"
          echo "      Turbo: Team: ${{ vars.TURBO_TEAM }}, TOKEN: ${{ secrets.TURBO_TOKEN }}"
          echo "————————————————————————————————————————————————————————————"

          docker compose build

          docker image ls

      - name: Push images
        run: docker compose push
